spring:
  datasource:
    url: jdbc:mysql://localhost/algafoodapi?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root
  flyway:
    locations: classpath:db/migration,classpath:db/testdata
  jackson:
    deserialization:
      fail-on-unknown-properties: true
      fail-on-ignored-properties: true
#    property-naming-strategy: SNAKE_CASE
  jpa:
#    generate-ddl: true
#    hibernate:
#      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false